### ISSUE TITLE
Expo项目Android构建失败

### ISSUE THREAD

**Issue by zjcdaniell** [yidun/quickpass-plugin-rn#3]
使用Expo创建的RN项目Android构建报`Manifest merger failed`

#### 复现步骤：
```bash
npx create-expo-app@latest

# in project floder
npx expo install @yidun/quickpass-plugin-rn
npx expo run:android
```

#### 错误信息如下:
```bash
npx expo run:android
› Building app...
Configuration on demand is an incubating feature.

> Configure project :yidun_quickpass-plugin-rn
WARNING: Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :expo

Using expo modules
  - expo-asset (10.0.9)
  - expo-constants (16.0.2)
  - expo-file-system (17.0.1)
  - expo-font (12.0.7)
  - expo-keep-awake (13.0.2)
  - expo-modules-core (1.12.15)
  - expo-splash-screen (0.27.5)
  - expo-system-ui (3.0.6)
  - expo-web-browser (13.0.3)


> Configure project :react-native-reanimated
Android gradle plugin: 8.2.1
Gradle: 8.6
WARNING: The specified Android SDK Build Tools version (30.0.3) is ignored, as it is below the minimum supported version (34.0.0) for Android Gradle Plugin 8.2.1.
Android SDK Build Tools 34.0.0 will be used.
To suppress this warning, remove "buildToolsVersion '30.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :yidun_quickpass-plugin-rn:processDebugManifest
package="com.reactlibrary" found in source AndroidManifest.xml: /Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@yidun/quickpass-plugin-rn/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactlibrary" from the source AndroidManifest.xml: /Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@yidun/quickpass-plugin-rn/android/src/main/AndroidManifest.xml.

> Task :app:processDebugMainManifest FAILED
/Users/render/Desktop/expo-demo/quickpassdemo/android/app/src/debug/AndroidManifest.xml:14:162-188 Error:
        Attribute application@allowBackup value=(true) from AndroidManifest.xml:14:162-188
        is also present at [io.github.yidun:quicklogin:3.4.3.1] AndroidManifest.xml:15:18-45 value=(false).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:6:5-162 to override.

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:14:162-188
        is also present at [io.github.yidun:quicklogin:3.4.3.1] AndroidManifest.xml:15:18-45 value=(false).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:6:5-162 to override.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 7s
104 actionable tasks: 10 executed, 2 from cache, 92 up-to-date
Error: /Users/render/Desktop/expo-demo/quickpassdemo/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: /Users/render/Desktop/expo-demo/quickpassdemo/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at spawnAsync (/Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/Users/render/Desktop/expo-demo/quickpassdemo/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)
```

**Comment by zjcdaniell** [comment]
删掉`android:allowBackup="true"`后构建正常
